networks:
  projeto-produtos:
    driver: bridge

services:
  postgres:
    image: postgres:latest
    container_name: postgres_api_person_registration
    restart: always
    environment:
      POSTGRES_DB: bd_apipersonregistration
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - projeto-person-registration
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d bd_apipersonregistration"]
      interval: 10s
      timeout: 5s
      retries: 5

  api_person_registration:
    build:
      context: ./apiPersonRegistration
    container_name: api_person_registration
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/bd_apipersonregistration
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "8081:8080" # Porta 8081 no host mapeada para 8080 no container
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - projeto-person-registration
  
  mongodb:
    image: mongo:latest
    container_name: mongodb-container
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - projeto-person-registration

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-container
    ports:
      - "5672:5672"    
      - "15672:15672" 
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - projeto-person-registration

  #web-produtos:
  #  build:
  #    context: ./webProdutos
  #  container_name: web_produtos
  #  restart: always
  #  ports:
  #    - "4200:4200" # Porta 4200 no host mapeada para 4200 no container
  #  networks:
  #    - projeto-person-registration

volumes:
  postgres_data:
