version: '3.8'

services:
  # Aplicação React em produção
  web-person-registration:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web-person-registration
    ports:
      - "3031:3031"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3031/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Aplicação em modo desenvolvimento (opcional)
  web-person-registration-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: web-person-registration-dev
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_API_BASE_URL=http://api_person_registration:8080
    command: npm run dev
    profiles:
      - dev
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
